export const cartItems = [
  { name: 'Apple', price: 120, inStock: 3 },
  { name: 'Banana', price: 50, inStock: 5 },
  { name: 'Orange', price: 6, inStock: 2 },
  { name: 'PineApple', price: 2, inStock: 2 },
  { name: 'Coconut', price: 90, inStock: 2 },
  { name: 'Peach', price: 45, inStock: 2 },
  { name: 'Mango', price: 70, inStock: 4 },
  { name: 'Grapes', price: 30, inStock: 3 },
  { name: 'Watermelon', price: 120, inStock: 1 },
  { name: 'Cherry', price: 80, inStock: 2 },
  { name: 'Pear', price: 55, inStock: 3 },
  { name: 'Kiwi', price: 60, inStock: 2 },
  { name: 'Strawberry', price: 40, inStock: 5 },
  { name: 'Blueberry', price: 75, inStock: 2 },
  { name: 'Raspberry', price: 90, inStock: 3 },
  { name: 'Pomegranate', price: 100, inStock: 1 },
  { name: 'Blackberry', price: 55, inStock: 4 },
  { name: 'Apricot', price: 35, inStock: 3 },
  { name: 'Plum', price: 30, inStock: 2 },
  { name: 'Lemon', price: 10, inStock: 5 },
  { name: 'Lime', price: 15, inStock: 2 },
  { name: 'Cantaloupe', price: 80, inStock: 1 },
  { name: 'Honeydew', price: 70, inStock: 2 },
  { name: 'Fig', price: 50, inStock: 3 },
  { name: 'Guava', price: 65, inStock: 2 },
]
